apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
spec:
  project: default
  source:
    path: kubernetes/auth
    repoURL: { { .Values.spec.source.repoURL } }
    targetRevision: { { .Values.spec.source.targetRevision } }
  destination:
    namespace: argocd
    server: { { .Values.spec.destination.server } }
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
