---
# Source: chart/templates/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user
spec:
  project: default
  source:
    path: kubernetes/user
    repoURL: https://github.com/DrobyshevAlex/kubernetes-gprc-linkerd-load-balancing.git
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
