kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-user
  labels:
    app: app-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-user
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-user
    spec:
      containers:
        - name: app-user
          image: ghcr.io/drobyshevalex/app-user:latest
          imagePullPolicy: Always
          env:
            - name: GRPC_PORT
              value: "50051"
      terminationGracePeriodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: app-user
  labels:
    app: app-user
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 50051
  selector:
    app: app-user
