apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user
spec:
  hosts:
    - "app-user"
  http:
    - route:
        - destination:
            host: app-user
            port:
              number: 50051
      retries:
        attempts: 3
        retryOn: connect-failure,refused-stream,5xx,unavailable,internal
